### ISSUE TITLE
run_opt example

### ISSUE THREAD

**Issue by joyo44** [joanibal/pyAVL#21]
Hello @joanibal ,

I'm trying to run the run_opt example without success - CL and CM constraints are not matched.

I have installed openmdao 3.30.0 and pyoptsparse 2.20.2 on Ubuntu 20.04.

Find attached my example folder with additional outputs/reports.

OpenMdao is new to me, so I have no clue what's going wrong and it would be very nice if
you can give some help.

Thanks in advance.

John

[Opti.zip](https://github.com/joanibal/pyAVL/files/13850069/Opti.zip)

**Comment by joanibal** [comment]
Hey John, 

I'm at Scitech this week so I just recently saw this. Did you end up finding a solution to your problem? I suspect that the optimization example in the repo needs to be updated to use the newer pyavl openMDAO wrapper. 

Best,
Josh

**Comment by joanibal** [comment]
Pull request #22 should fix your issue. Checkout the updated example optimization run script.
