### ISSUE TITLE
Missing Body-File in AVL Geometrie output

### ISSUE THREAD

**Issue by joyo44** [joanibal/pyAVL#31]
Hey Josh,

writing the optimized geometry with "...avlsolver.solver.avl.write_geom_file(OptGeoFile)" has no body data included (if
available).

Cheers,
John

**Comment by joanibal** [comment]
Yes, let me see what I can do about that.

**Comment by joanibal** [comment]
`v1.6.3` was just released and should address your issue. Just `pip install pyavl-wrapper --upgrade`
I'm closing this, but please reopen if you are still having problems.

**Comment by joanibal** [comment]
There was a hiccup with the pypi upload. `v1.6.3` is there now.
